In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect('inventory.db')

In [3]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
tables

          name
0  gold prices
1         gold
2       silver
3          oil

In [4]:
for table in tables['name']:
    print('-'*50, f'{table}', '-'*50)
    print('Counts of records: ', pd.read_sql_query(f"SELECT COUNT(*) as count FROM {table}", conn)['count'].values[0])
    display(pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5", conn))

-------------------------------------------------- gold prices --------------------------------------------------
Counts of records:  130

,index,Date,Close,High,Low,Open,Volume
0,0,2025-10-10 00:00:00.000000,3975.899902,4012.000000,3945.500000,3957.000000,1697
1,1,2025-10-13 00:00:00.000000,4108.600098,4111.000000,4016.000000,4016.000000,1697
2,2,2025-10-14 00:00:00.000000,4138.700195,4160.100098,4085.800049,4131.700195,2424
3,3,2025-10-15 00:00:00.000000,4176.899902,4210.600098,4145.000000,4145.000000,3287
4,4,2025-10-16 00:00:00.000000,4280.200195,4307.000000,4196.600098,4198.799805,4705

-------------------------------------------------- gold --------------------------------------------------
Counts of records:  130

,index,Date,Close,High,Low,Open,Volume
0,0,2025-10-10 00:00:00.000000,3975.899902,4012.000000,3945.500000,3957.000000,1697
1,1,2025-10-13 00:00:00.000000,4108.600098,4111.000000,4016.000000,4016.000000,1697
2,2,2025-10-14 00:00:00.000000,4138.700195,4160.100098,4085.800049,4131.700195,2424
3,3,2025-10-15 00:00:00.000000,4176.899902,4210.600098,4145.000000,4145.000000,3287
4,4,2025-10-16 00:00:00.000000,4280.200195,4307.000000,4196.600098,4198.799805,4705

-------------------------------------------------- silver --------------------------------------------------
Counts of records:  130

,index,Date,Close,High,Low,Open,Volume
0,0,2025-10-10 00:00:00.000000,46.938000,48.290001,46.930000,46.930000,453
1,1,2025-10-13 00:00:00.000000,50.130001,50.494999,49.340000,49.340000,453
2,2,2025-10-14 00:00:00.000000,50.313999,51.985001,48.535000,51.259998,249
3,3,2025-10-15 00:00:00.000000,51.073002,51.575001,50.845001,50.939999,102
4,4,2025-10-16 00:00:00.000000,53.022999,53.105000,51.785000,52.509998,356

-------------------------------------------------- oil --------------------------------------------------
Counts of records:  130

,index,Date,Close,High,Low,Open,Volume
0,0,2025-10-10 00:00:00.000000,58.900002,61.669998,58.220001,61.490002,339103
1,1,2025-10-13 00:00:00.000000,59.490002,60.169998,59.000000,59.000000,339103
2,2,2025-10-14 00:00:00.000000,58.700001,59.820000,57.680000,59.580002,259200
3,3,2025-10-15 00:00:00.000000,58.270000,59.419998,58.200001,58.599998,224919
4,4,2025-10-16 00:00:00.000000,57.459999,59.110001,57.259998,58.770000,203866